# Generated by Django 2.0.4 on 2018-05-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20180501_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(),
        ),
    ]
