# Generated by Django 2.0.4 on 2018-05-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20180501_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
