# Generated by Django 2.0.4 on 2018-05-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20180508_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='url_slug',
            field=models.SlugField(default='replace-me'),
            preserve_default=False,
        ),
    ]
