# Generated by Django 2.0.4 on 2018-05-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_dish_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
