# Generated by Django 2.0.4 on 2018-05-16 00:39

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20180515_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
    ]
