# Generated by Django 2.0.4 on 2018-05-17 00:43

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20180515_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='blah', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=localflavor.us.models.USStateField(default='blah', max_length=2),
            preserve_default=False,
        ),
    ]
